namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_SPOTIFY_APP_CLIENT_ID: string
    NEXT_PUBLIC_SPOTIFY_APP_CLIENT_SECRET: string
    NEXT_PUBLIC_SPOTIFY_LOGIN_REDIRECT_URL: string
    NEXT_PUBLIC_WEBSITE_URL: string
    NEXT_PUBLIC_DEVELOPER_WEBSITE_URL: string
  }
}
